# Generated by Django 4.2.24 on 2026-02-09 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0001_initial"),
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("behavioral", "Behavioral"),
                            ("technical", "Technical"),
                            ("mixed", "Mixed"),
                        ],
                        default="behavioral",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("analyzed", "Analyzed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("overall_feedback", models.TextField(blank=True)),
                ("behavioral_insights", models.JSONField(blank=True, default=dict)),
                ("emotion_summary", models.JSONField(blank=True, default=dict)),
                ("question_count", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_order", models.IntegerField(default=0)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="mock_videos/"),
                ),
                ("transcript", models.TextField(blank=True)),
                ("ai_score", models.FloatField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("emotion_data", models.JSONField(blank=True, default=dict)),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Recording duration in seconds"
                    ),
                ),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_responses",
                        to="questions.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="interviews.mocksession",
                    ),
                ),
            ],
            options={
                "ordering": ["question_order"],
                "unique_together": {("session", "question")},
            },
        ),
    ]
